      TypeError: Cannot read properties of undefined (reading 'navigationId')
            at Object.get navigationId [as navigationId] (node_modules/@angular/router/fesm2020/router.mjs:4979:43)
            at forEach (projects/webo-mockslib/src/lib/webo/mock-provider.ts:34:91)
            at Array.forEach (<anonymous>)
            at MockProvider.autoMock (projects/webo-mockslib/src/lib/webo/mock-provider.ts:32:18)
            at new MockProvider (projects/webo-mockslib/src/lib/webo/mock-provider.ts:11:28)
            at WeboSandboxTestBed.buildProviders (projects/webo-mockslib/src/lib/webo/abstract-testbed.ts:54:11)
            at WeboSandboxTestBed.WEBOSANDBOX_TEST_BED [as forComponent] (projects/webo-mockslib/src/lib/webo/abstract-testbed.ts:37:30)
